### ISSUE TITLE
Default of poisson_multinomial throws DivisionByZero Error

### ISSUE THREAD

**Issue by tdsone** [calico/baskerville#39]
Hey there :)

The implementation of [poisson_multinomial](https://github.com/calico/baskerville/blob/9d51a099059b2365db0d6dbdc9dc9f71dcc0cda1/src/baskerville/metrics.py#L114) suggests that 1 is a good default for the weight_range. In practice it raises `RuntimeWarning: divide by zero encountered in scalar divide` since np.log(weight_range) = 0 for weight_range = 1.

Best
Timon

**Comment by davek44** [comment]
This is a new feature that we're playing around with. All published models would use weight_range=1. I pushed a fix that avoid giving this warning.

**Comment by tdsone** [comment]
Thanks Dave!
